apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentportfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentportfolio
  template:
    metadata:
      labels:
        app: studentportfolio
    spec:
      containers:
      - name: studentportfolio
        image: ghcr.io/rrcsmehta3/studentportfolio:latest
